pekko.actor {
  serialization-bindings {
    "biz.lobachev.annette.org_structure.impl.hierarchy.entity.HierarchyEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.org_structure.impl.role.OrgRoleEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.org_structure.impl.category.CategoryEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.org_structure.impl.hierarchy.entity.HierarchyEntity$Event" = jackson-json
    "biz.lobachev.annette.org_structure.impl.role.OrgRoleEntity$Event" = jackson-json
    "biz.lobachev.annette.org_structure.impl.category.CategoryEntity$Event" = jackson-json
    "org.apache.pekko.Done" = pekko-misc
    "org.apache.pekko.actor.Address" = pekko-misc
    "org.apache.pekko.remote.UniqueAddress" = pekko-misc
  }
}
