pekko.actor {
  serialization-bindings {
    "biz.lobachev.annette.cms.impl.blogs.blog.BlogEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.blogs.post.PostEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.blogs.category.BlogCategoryEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.space.SpaceEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.page.PageEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.category.SpaceCategoryEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.files.FileEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.home_pages.HomePageEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.cms.impl.blogs.blog.BlogEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.blogs.post.PostEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.blogs.category.BlogCategoryEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.space.SpaceEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.page.PageEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.pages.category.SpaceCategoryEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.files.FileEntity$Event" = jackson-json
    "biz.lobachev.annette.cms.impl.home_pages.HomePageEntity$Event" = jackson-json
    "org.apache.pekko.Done" = pekko-misc
    "org.apache.pekko.actor.Address" = pekko-misc
    "org.apache.pekko.remote.UniqueAddress" = pekko-misc
  }
}
