include "application.conf"

pekko.grpc.client {
  application.host = "application"
  service-catalog.host = "service-catalog"
  persons.host = "persons"
  org-structure.host = "org-structure"
  authorization.host = "authorization"
  principal-groups.host = "principal-groups"
  cms.host = "cms"
}
pekko.grpc.client.application.port = 9000
pekko.grpc.client.service-catalog.port = 9000
pekko.grpc.client.persons.port = 9000
pekko.grpc.client.org-structure.port = 9000
pekko.grpc.client.authorization.port = 9000
pekko.grpc.client.principal-groups.port = 9000
pekko.grpc.client.cms.port = 9000
