pekko.actor {
  serialization-bindings {
    "biz.lobachev.annette.persons.impl.person.PersonEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.persons.impl.category.CategoryEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.persons.impl.person.PersonEntity$Event" = jackson-json
    "biz.lobachev.annette.persons.impl.category.CategoryEntity$Event" = jackson-json
    "org.apache.pekko.Done" = pekko-misc
    "org.apache.pekko.actor.Address" = pekko-misc
    "org.apache.pekko.remote.UniqueAddress" = pekko-misc
  }
}
