pekko.actor {
  serialization-bindings {
    "biz.lobachev.annette.service_catalog.impl.category.CategoryEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.scope.ScopeEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.scope_principal.ScopePrincipalEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.item.ServiceItemEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.service_principal.ServicePrincipalEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.category.CategoryEntity$Event" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.scope.ScopeEntity$Event" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.scope_principal.ScopePrincipalEntity$Event" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.item.ServiceItemEntity$Event" = jackson-json
    "biz.lobachev.annette.service_catalog.impl.service_principal.ServicePrincipalEntity$Event" = jackson-json
    "org.apache.pekko.Done" = pekko-misc
    "org.apache.pekko.actor.Address" = pekko-misc
    "org.apache.pekko.remote.UniqueAddress" = pekko-misc
  }
}
