# Play application config
play {
  http {
    secret.key = "changeme-spike-only-not-for-production"
    secret.key = ${?PLAY_SECRET}
  }
  server {
    provider = "play.core.server.PekkoServerProvider"
    pekko {
      http.server.preview.enable-http2 = on
    }
  }
  modules {
    enabled += spike.hello.GrpcServerModule
  }
}

pekko {
  loglevel = INFO
  http.server.preview.enable-http2 = on
  actor.allow-java-serialization = on
}
