pekko.actor {
  serialization-bindings {
    "biz.lobachev.annette.subscription.impl.subscription.SubscriptionEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.subscription.impl.subscription_type.SubscriptionTypeEntity$CommandSerializable" = jackson-json
    "biz.lobachev.annette.subscription.impl.subscription.SubscriptionEntity$Event" = jackson-json
    "biz.lobachev.annette.subscription.impl.subscription_type.SubscriptionTypeEntity$Event" = jackson-json
    "org.apache.pekko.Done" = pekko-misc
    "org.apache.pekko.actor.Address" = pekko-misc
    "org.apache.pekko.remote.UniqueAddress" = pekko-misc
  }
}
