include "application.dev.conf"

pekko {
  remote.artery.canonical.hostname = "127.0.0.1"
  remote.artery.canonical.port = 17365
  cluster.seed-nodes = ["pekko://cms@127.0.0.1:17365"]
}
annette.http.host = "0.0.0.0"
annette.http.port = 9000
